zuul:
  prefix: /api
  routes:
    products:
      path: /products/**
      url: http://products-service:5000
    orders:
      path: /orders/**
      url: http://orders-service:3000

eureka:
  client:
    enabled: false