zuul:
  prefix: /api
  routes:
    products:
      path: /products/**
      url: products-service:5000
    orders:
      path: /orders/**
      url: orders-service:3000

eureka:
  client:
    enabled: false